services:
  - type: web
    name: minio-storage
    env: docker
    dockerfilePath: ./Dockerfile.minio
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        value: henrydepchai
      - key: MINIO_ROOT_PASSWORD
        value: vodichtoanvutru